version: '3.7'
services:
  # Infrastructure
  database:
    container_name: 'nucleus-database'
    image: "postgres:11"
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./db-provision/pg:/docker-entrypoint-initdb.d/
